server:
  port: 8082
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/pedido?createDatabaseIfNotExist=true
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
    connection-timeout: 5s
  # kafka:
  #   bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: cadastrarVenda;updateVenda;cancelarVenda;venda;
    stream:
      bindings:
        cadastrarVenda-in-0:
          destination: cad.venda.entrada
        cadastrarVenda-out-0:
          destination: cad.venda.saida
        updateVenda-in-0:
          destination: up.venda.entrada
        updateVenda-out-0:
          destination: up.venda.saida
        cancelarVenda-in-0:
          destination: cancelar.venda.entrada
        cancelarVenda-out-0:
          destination: cancelar.venda.saida
        venda-in-0:
          destination: get.venda.entrada
        venda-out-0:
          destination: get.venda.saida
    discovery:
      enabled: true
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  circuitBreaker:
    instances:
      estoque:
        register-health-indicator: true
        wait-duration-in-open-state:
          seconds: 10
        record-exceptions:
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.InternalServerError
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - feign.FeignException.FeignServerException
          - org.springframework.web.client.ResourceAccessException
      usuarioService:
        register-health-indicator: true
        wait-duration-in-open-state:
          seconds: 5
        record-exceptions:
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.InternalServerError
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - feign.FeignException.FeignServerException
          - org.springframework.web.client.ResourceAccessException
  bulkhead:
    instances:
      bulkHeadEstoque:
        max-wait-duration:
          seconds: 0.002
        max-concurrent-calls: 20
      bulkHeadUsuarioService:
        max-wait-duration:
          seconds: 0.002
        max-concurrent-calls: 50
  retry:
    instances:
      retryEstoque:
        max-attempts: 10
        wait-duration:
          seconds: 10
        retry-exceptions:
          - java.util.concurrent.TimeoutException
      retryUsuarioService:
        max-attempts: 10
        wait-duration:
          seconds: 10
        retry-exceptions:
          - java.util.concurrent.TimeoutException