server:
  port: 8081
  servlet:
    context-path: /catalogo
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/loja
    username: postgres
    password: sgeopass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
