server:
  port: 8081
  servlet:
    context-path: /catalogo
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://172.29.16.1:5432/loja
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
  cloud:
    config:
      uri: http://172.29.16.1:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
  flyway:
    baselineOnMigrate: true
eureka:
  client:
    instance:
      preferIpAdress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
