server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/catalogo?createDatabaseIfNotExist=true
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
    connection-timeout: 5s
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: criarProduto
    stream:
      bindings:
        criarProduto-in-0:
          destination: criar.produto.entrada
        criarProduto-out-0:
          destination: criar.produto.saida
    discovery:
      enabled: true
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      label: main
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
