server:
  port: 8085
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/estoque?createDatabaseIfNotExist=true
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
    connection-timeout: 5s
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: criarEstoqueProduto;updateEstoqueProduto;validarEAtualizarEstoqueVenda;
    stream:
      bindings:
        criarEstoqueProduto-in-0:
          destination: criar.estoque.produto.entrada
        criarEstoqueProduto-out-0:
          destination: criar.estoque.produto.saida
        updateEstoqueProduto-in-0:
          destination: update.estoque.produto.entrada
        updateEstoqueProduto-out-0:
          destination: update.estoque.produto.saida
        validarEAtualizarEstoqueVenda-in-0:
          destination: validar.atualizar.estoque.venda.entrada
        validarEAtualizarEstoqueVenda-out-0:
          destination: cancelar.venda.entrada
    discovery:
      enabled: true
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
eureka:
  instance:
    preferIpAddress: true
    # hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  circuitBreaker:
    instances:
      circuitBreakerCatalogo:
        register-health-indicator: true
        wait-duration-in-open-state:
          seconds: 10
        record-exceptions:
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.InternalServerError
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - feign.FeignException.FeignServerException
          - org.springframework.web.client.ResourceAccessException
  bulkhead:
    instances:
      bulkHeadCatalogo:
        max-wait-duration:
          seconds: 0.002
        max-concurrent-calls: 50
  retry:
    instances:
      retryCatalogo:
        max-attempts: 10
        wait-duration:
          seconds: 10
        retry-exceptions:
          - java.util.concurrent.TimeoutException
