server:
  port: 8080
eureka:
  instance:
    preferIpAdress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    webclient:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"