server:
  port: 8080
eureka:
  instance:
    preferIpAdress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: health,info,refresh,routes