server:
  port: 8089
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/usuario
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
    connection-timeout: 5s
  cloud:
    stream:
      function:
        definition: criarCliente,getCliente
      bindings:
        criarCliente-in-0:
          destination: criar.cliente.entrada.dados
        # getCliente-in-0:
        #   destination: buscar.cliente.id.entrada.dados
        # getCliente-out-0:
        #   destination: buscar.cliente.id.saida.dados
    discovery:
      enabled: true
    config:
      uri: http://locahost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"